Update the PR status on GitHub as the tests progress

diff --git a/validate b/validate
--- a/validate
+++ b/validate
@@ -8,13 +8,35 @@
 # Note: this script relies on `visDQMUpload` and `visDQMUtils.py` being available in the same directory.
 # If they are missing they are automatically downloaded from https://github.com/rovere/dqmgui/ .
 
+# check if we are able to post comments on GitHub
+POST_COMMENT=true
+EDIT_COMMENT=true
+OAUTH_TOKEN=
+ISSUE_NUMBER=
+COMMENT_ID=
+if ! which "curl" > /dev/null; then
+  echo "Command \"curl\" not found." 1>&2
+  POST_COMMENT=false
+fi
+if ! which "jq" > /dev/null; then
+  echo "Command \"jq\" not found." 1>&2
+  EDIT_COMMENT=false
+fi
+if [ -f ~/.patatrack-validation.oauth ]; then
+  OAUTH_TOKEN=$(< ~/.patatrack-validation.oauth)
+else
+  echo "OAUTH token not found." 1>&2
+  POST_COMMENT=false
+fi
+[ $POST_COMMENT ] || echo "The report will not be posted to GitHub." 1>&2
+[ $POST_COMMENT ] && [ $EDIT_COMMENT ] || "Only the final report will be posted to GitHub." 1>&2
+
 # hash of this script
 SCRIPTHASH=$(sha1sum ${BASH_SOURCE[0]} | cut -d' ' -f1)
 
 BASE=$(mktemp -d -p $PWD run.XXXXXXXXXX)
 [ -d $BASE ] || exit 1
 REPORT=$BASE/report.md
-JSON=$BASE/report.json
 
 # save the original file descriptors, then redirect all output and errors to a log file
 exec 3>&1 4>&2
@@ -76,7 +98,85 @@ source /data/cmssw/cmsset_default.sh
 
 function report() {
   echo "$@" >> $REPORT
-  echo -n "$@\r\n" | sed -e's/"/\\"/g' >> $JSON
+}
+
+function can_post_comment() {
+  $POST_COMMENT && [ "$ISSUE_NUMBER" ]
+}
+
+function can_update_comment() {
+  can_post_comment && $EDIT_COMMENT && [ "$COMMENT_ID" ]
+}
+
+# Post a comment to a GitHub issue
+#
+# Usage:
+#   post_comment BODY
+#
+# Any format accepted by curl is valid for BODY. For example,
+# the format "@FILE" will use the content of FILE.
+#
+function post_comment() {
+  can_post_comment || return
+  local BODY="$1"       # body of the message, wrapped in JSON format (see https://developer.github.com/v3/issues/comments/ )
+  local RESPONSE
+  if ! RESPONSE=$(curl -s -S -H "Authorization: token $OAUTH_TOKEN" -X "POST" "https://api.github.com/repos/cms-patatrack/cmssw/issues/$ISSUE_NUMBER/comments" -d "$BODY"); then
+    # failed; disable further posting
+    POST_COMMENT=false
+    EDIT_COMMENT=false
+  elif $EDIT_COMMENT; then
+    # success; set the comment id for further editin
+    COMMENT_ID=$(echo "$RESPONSE" | jq ".id")
+  fi
+}
+
+# Update a comment on a GitHub issue
+#
+# Usage:
+#   update_comment BODY
+#
+# Any format accepted by curl is valid for BODY. For example,
+# the format "@FILE" will use the content of FILE.
+#
+function update_comment() {
+  can_update_comment || return
+  local BODY="$1"       # body of the message, wrapped in JSON format (see https://developer.github.com/v3/issues/comments/ )
+  local RESPONSE
+  if ! RESPONSE=$(curl -s -S -H "Authorization: token $OAUTH_TOKEN" -X "PATCH" "https://api.github.com/repos/cms-patatrack/cmssw/issues/comments/$COMMENT_ID" -d "$BODY"); then
+    # failed; disable further posting
+    POST_COMMENT=false
+    EDIT_COMMENT=false
+  fi
+}
+
+function upload_final_report() {
+  local JSON=$(mktemp -p $BASE report.XXXXXXXXXX.json)
+  {
+    echo -e -n '{\n    "body": "'
+    cat $BASE/report.md | tr '\n' '\r' | sed -e's/\r/\\r\\n/g' -e's/"/\\"/g'
+    echo -e '"\n}'
+  } > $JSON
+  if can_update_comment; then
+    update_comment "@$JSON"
+  elif can_post_comment; then
+    post_comment "@$JSON"
+  fi
+  #rm -f $JSON
+}
+
+function upload_report() {
+  local JSON=$(mktemp -p $BASE report.XXXXXXXXXX.json)
+  {
+    echo -e -n '{\n    "body": "'
+    cat $BASE/report.md | tr '\n' '\r' | sed -e's/\r/\\r\\n/g' -e's/"/\\"/g'
+    echo -e "\\\r\\\n\\\r\\\n:construction: Validation running at $(hostname):$BASE ...\"\n}"
+  } > $JSON
+  if can_update_comment; then
+    update_comment "@$JSON"
+  elif can_post_comment; then
+    post_comment "@$JSON"
+  fi
+  #rm -f $JSON
 }
 
 function apply() {
@@ -719,7 +819,12 @@ function upload_log_files() {
 
 # main
 echo > $REPORT
-echo -e -n '{\n    "body": "' > $JSON
+
+# upload the report to the last PR given on the command line
+for ISSUE_NUMBER in "$@"; do true; done
+
+# if we can edit the comment after posting it, create an empty comment as a starting point
+can_post_comment && $EDIT_COMMENT && upload_report
 
 # set up the reference release
 report "### Validation summary"
@@ -727,6 +832,7 @@ setup_release "reference" CMSSW_10_2_1
 report "Reference release [CMSSW_10_2_1](https://github.com/cms-sw/cmssw/tree/CMSSW_10_2_1) at $(< $BASE/reference/hash)"
 build_matrix "reference" "$REFERENCE_WORKFLOW"
 DIRECTORIES="reference"
+upload_report
 
 # set up the current development branch
 setup_patatrack_release "development" CMSSW_10_2_1_Patatrack CMSSW_10_2_X_Patatrack
@@ -734,6 +840,7 @@ setup_patatrack_release "development" CMSSW_10_2_1_Patatrack CMSSW_10_2_X_Patatr
 report "Development branch [CMSSW_10_2_X_Patatrack](https://github.com/$REPOSITORY/cmssw/tree/CMSSW_10_2_X_Patatrack) at $(< $BASE/development/hash)"
 build_matrix "development" "$WORKFLOWS"
 DIRECTORIES+=" development"
+upload_report
 
 # set up the development branch plus the PR(s) to be tested
 if [ "$*" ]; then
@@ -750,6 +857,7 @@ if [ "$*" ]; then
   DIRECTORIES+=" testing"
 fi
 report
+upload_report
 
 # compute a unique hash for this validation run
 JOBID=$({ echo $SCRIPTHASH; cat $(apply_and_glob "$BASE/%/hash" $DIRECTORIES); } | sha1sum | cut -d' ' -f1)
@@ -757,12 +865,16 @@ echo $JOBID > $BASE/jobid
 
 # run the workflows
 run_workflows $DIRECTORIES
+upload_report
 # make validation plots
 make_validation_plots $DIRECTORIES
+upload_report
 # upload DQM plots to the GUI
 upload_dqm_plots $DIRECTORIES
+upload_report
 # upload nvprof profiles
 upload_profiles $DIRECTORIES
+upload_report
 
 # restore the original descriptors, close and upload the log files
 exec 1>&3- 2>&4-
@@ -772,9 +884,5 @@ echo "This report can be found at $REPORT:"
 echo
 cat $REPORT
 
-echo -e '"\n}' >> $JSON
-
 # post the report to GitHub
-if [ "$*" ] && [ -f ~/.patatrack-validation.oauth ]; then
-  curl -H "Authorization: token $(< ~/.patatrack-validation.oauth)" -X POST "https://api.github.com/repos/cms-patatrack/cmssw/issues/$1/comments" -d "@$JSON"
-fi
+upload_final_report
